networks:
  social-butterfly:
    external: false

services:
  users:
    build:
      context: ./users/
      dockerfile: dockerfile
    env_file:
      - ./users/src/config/.env.config
    networks:
      - social-butterfly
    ports:
      - 3000:3000
    restart: always
  
  events:
    build:
      context: ./events/
      dockerfile: dockerfile
    env_file:
      - ./events/src/config/.env.config
    networks:
      - social-butterfly
    ports:
      - 3001:3001
    restart: always

  consumer:
    build:
      context: ./consumer
      dockerfile: dockerfile
    env_file:
      - ./consumer/src/config/.env.config
    ports:
      - 3002:3002
    networks:
      - social-butterfly
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - social-butterfly
    ports:
      - '5672:5672'
      - '8080:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: always